name: example
on: push
jobs:
  Compile_release:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Compile
        run: cmake --build build
   
