name: example
on: push
jobs:
  Compile_release:
    runs-on: ubuntu-latest
    steps:
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Compile
        run: cmake --build build
   
